title: Aashutosh A Mishra
logo: display_picture.png
# github_username: yourusername
# description: text below image
# show_downloads: true
theme: jekyll-theme-minimal

# Add a custom CSS file
markdown: kramdown
sass:
  style: compressed

# Point to your custom CSS file
include:
  - assets/css/custom.css
